### PR TITLE
Update GettingStarted.md

### PR DESCRIPTION
**Pull request by uxkjaer**
Added the check on the build script. This took me two hours to find.

### CODE REVIEW

**Comment by marianfoo** [comment]
Hi Jakob, thanks for opening the PR.
I'm sorry it took you so much time.
i mention it here on the getting started page:
https://docs.spreadsheet-importer.com/pages/GettingStarted/#setup-decentralized-deployment
3\. Add `--all` to your build script in the package.json

```json
"scripts": {
  ...
  "build": "ui5 build --config=ui5.yaml --all --clean-dest --dest dist",
  ...
}
```

Do you mean this?

**Comment by uxkjaer** [comment]
I guess I need to pay more attention to the doco 😂

**Comment by marianfoo** [comment]
No worries :)

> doco

I see you use ausie slang :D

**Comment by uxkjaer** [comment]
Haha no one here finishes their senten.

See what I did there 😂

When do we see you in Australia?

**Comment by marianfoo** [comment]
Till someone pays for my flight 😁
Would be great to be back some time in the future

**Pull request closed without merging**
